-- AddPlusOnesAndFamilyHeadcountToGuest
ALTER TABLE "Guest" ADD COLUMN "plusOnes" INTEGER DEFAULT 0;
ALTER TABLE "Guest" ADD COLUMN "adults" INTEGER DEFAULT 1;
ALTER TABLE "Guest" ADD COLUMN "children" INTEGER DEFAULT 0;

-- AddGuestSettingsToEvent
ALTER TABLE "Event" ADD COLUMN "privateGuestList" BOOLEAN DEFAULT false;
ALTER TABLE "Event" ADD COLUMN "allowPlusOnes" BOOLEAN DEFAULT false;
ALTER TABLE "Event" ADD COLUMN "maxPlusOnes" INTEGER DEFAULT 0;
ALTER TABLE "Event" ADD COLUMN "allowMaybeRSVP" BOOLEAN DEFAULT true;
ALTER TABLE "Event" ADD COLUMN "allowFamilyHeadcount" BOOLEAN DEFAULT false;
ALTER TABLE "Event" ADD COLUMN "limitEventCapacity" BOOLEAN DEFAULT false;
ALTER TABLE "Event" ADD COLUMN "maxEventCapacity" INTEGER DEFAULT 0;
